### ISSUE TITLE
rename automationbroker.io package

### ISSUE THREAD

**Issue by rcernich** [AutomationBroker/broker-client-go#3]
At this risk of exposing myself as a go noob, I don't think we should be using dots in package names.  I also believe the package "name" should align with the folder name and `automationbroker.io` cannot be used as a package name.  This is most evident in pkg/apis/automationbroker.io/register.go.

This prevents the use of internal types, which will hinder the api evolution if a v2 is ever added.

**Comment by shawn-hurley** [comment]
The more I think about this, the less opposed to renaming the package I am. It appears that I may have gotten tunnel vision when I was making these. 

I don't think that anything here hinders or prevents an internal version of the API. It should be noted that these types are still under development and have not been finalized for outside use. I would not expect that using this library to interact with the brokers CRs will behave well. 

Also, versioning of the API will be a problem far outside the scope of this project. CRD's don't have the ability to version the APIs so there should only ever be one "version" or CRD of our resources in the cluster. In that case, I believe that we may not want to pursue internal types. If you're asking if we should do that, I think we need to get CRs that we are happy with for outside use before we start worrying about that.

**Comment by rcernich** [comment]
The issue is that the code generator uses this as the package name for some of the generated resources, i.e. `package automationbroker.io`, specifically for the internal listeners.  It also does seem to match the convention used by other go projects, where the folder name matches with the package name.

**Comment by shawn-hurley** [comment]
fixed with #7
