### ISSUE TITLE
rename Parameters struct to Parameter

### ISSUE THREAD

**Issue by mhrivnak** [AutomationBroker/broker-client-go#4]
The `Parameters` struct found [here](https://github.com/automationbroker/broker-client-go/blob/417a1c502/pkg/apis/automationbroker.io/v1/types.go#L90) represents a single parameter. I think it would make more sense with the singular name `Parameter`.

Any thoughts on or objections to that? Maybe the plural form chosen for a reason?

**Comment by shawn-hurley** [comment]
fixed with #7
